version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - ./knowledge_embedding:/app/knowledge_embedding
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_chatbot
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
